name: Lint and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop
      - release-*

jobs:
  lint:
    name: Lint and Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run 'prettier' code formatter
        run: yarn format:check

      - name: Run 'eslint' code linter
        run: yarn lint

  test:
    name: Test and Code Coverage
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run 'jest' test runner
        run: yarn test:coverage
